version: "3"
services:
  express:
    build: ./express
   # ports:
   #   - "3000:3000"
    networks:
      - parlament
    restart: on-failure
  react:
    build: ./react
    #ports:
    #  - "3001:3000"
    networks:
      - parlament
    #restart: on-failure
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sensei
      POSTGRES_PASSWORD: sensei
      POSTGRES_DB: sensei
    #ports:
    #  - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - parlament
    restart: on-failure
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - parlament
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "3030:3030"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - parlament
    depends_on:
      - react
      - express
    restart: on-failure
volumes:
  db-data:

networks:
  parlament:
