import { fromPairs } from "lodash";
import InputSimple from "./Input";

export { default as Span } from "./span";
export { default as Grid } from "./grid";
export { default as Form } from "./form";
export { default as Flex } from "./flex";
export { default as Text } from "./text";
export { default as Input } from "./Input";
export { default as Image } from "./image";
export { default as Button } from "./button";
export { default as Div } from "./simpleDiv";
export { default as Wrapper } from "./wrapper";
export { default as Content } from "./content";
export { default as CardWrapper } from "./card";
export { default as InputSimple } from "./Input";
export { default as Textarea } from "./textArea";
export { default as FileLink } from "./fileLink";
export { default as Popover } from "./popover";
export { default as EmojiPicker } from "./emojiPicker";
export { default as GlobalStyle } from "./globalStyle";
// export { default as GlobalStyle } from "./globalStyle";
